[options]
unmatched_exclude = [
  # Seems to be some test artifacts only on Windows.
  "bin/*.hip.exe",
]

# rocPRIM
[components.dbg."math-libs/rocPRIM/stage"]
[components.dev."math-libs/rocPRIM/stage"]
[components.doc."math-libs/rocPRIM/stage"]
[components.test."math-libs/rocPRIM/stage"]
include = [
  "bin/test_*",
  "bin/rocprim/CTestTestfile.cmake",
  "lib/libtest_linking_*.*",
]

# hipCUB
[components.dbg."math-libs/hipCUB/stage"]
[components.dev."math-libs/hipCUB/stage"]
[components.doc."math-libs/hipCUB/stage"]
[components.test."math-libs/hipCUB/stage"]
include = [
  "bin/test_*",
  "bin/hipcub/CTestTestfile.cmake",
]

# rocThrust
[components.dbg."math-libs/rocThrust/stage"]
[components.dev."math-libs/rocThrust/stage"]
[components.doc."math-libs/rocThrust/stage"]
[components.test."math-libs/rocThrust/stage"]
include = [
  "bin/test_*",
  "bin/*.hip",
  "bin/rocthrust/CTestTestfile.cmake",
]
